# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AndyNo.10
email: andyNumber10@gmail.com
description: This is a simple blog to share my ideas, concepts and my learning path.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andyNo10.github.io" # the base hostname & protocol for your site 
timezone: "Asia/Taipei"

twitter_username: 10Andyno
github_username:  andyNo10
linkedin_username: teng-yung-lin-b12950113
facebook_username: profile.php?id=100006239347841

# Build settings
markdown: kramdown

#pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
